# Generated by Django 5.2 on 2025-04-28 17:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('Income', 'Income'), ('Expenditure', 'Expenditure')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('staff_name', models.CharField(max_length=100)),
                ('credit_given', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DailyFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('previous_day_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('money_from_bank', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit_received', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit_given', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('google_pay_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_of_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sip_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('staff_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('chitty_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit_paid_out', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_expenditure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medicine_return', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extra_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_expenditure', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_purchase', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_credit_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_credit_left', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_google_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Wholesaler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('previous_credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_number', models.CharField(max_length=50)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_left', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wholesaler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jana.wholesaler')),
            ],
        ),
    ]
